package ar.edu.unju.edm.app.domain.util;

import java.util.ArrayList;
import java.util.List;

import ar.edu.unju.edm.app.domain.model.complements.Country;

public class CountryList {

    public static List<Country> get() {
        List<Country> list = new ArrayList<>();
        list.add(new Country("Afganistán", "AF"));
        list.add(new Country("Albania", "AL"));
        list.add(new Country("Alemania", "DE"));
        list.add(new Country("Andorra", "AD"));
        list.add(new Country("Angola", "AO"));
        list.add(new Country("Antigua y Barbuda", "AG"));
        list.add(new Country("Arabia Saudita", "SA"));
        list.add(new Country("Argelia", "DZ"));
        list.add(new Country("Argentina", "AR"));
        list.add(new Country("Armenia", "AM"));
        list.add(new Country("Australia", "AU"));
        list.add(new Country("Austria", "AT"));
        list.add(new Country("Azerbaiyán", "AZ"));
        list.add(new Country("Bahamas", "BS"));
        list.add(new Country("Baréin", "BH"));
        list.add(new Country("Bangladesh", "BD"));
        list.add(new Country("Barbados", "BB"));
        list.add(new Country("Bielorrusia", "BY"));
        list.add(new Country("Bélgica", "BE"));
        list.add(new Country("Belice", "BZ"));
        list.add(new Country("Benín", "BJ"));
        list.add(new Country("Bután", "BT"));
        list.add(new Country("Bolivia", "BO"));
        list.add(new Country("Bosnia y Herzegovina", "BA"));
        list.add(new Country("Botsuana", "BW"));
        list.add(new Country("Brasil", "BR"));
        list.add(new Country("Brunéi", "BN"));
        list.add(new Country("Bulgaria", "BG"));
        list.add(new Country("Burkina Faso", "BF"));
        list.add(new Country("Burundi", "BI"));
        list.add(new Country("Cabo Verde", "CV"));
        list.add(new Country("Camboya", "KH"));
        list.add(new Country("Camerún", "CM"));
        list.add(new Country("Canadá", "CA"));
        list.add(new Country("Catar", "QA"));
        list.add(new Country("Chad", "TD"));
        list.add(new Country("Chile", "CL"));
        list.add(new Country("China", "CN"));
        list.add(new Country("Chipre", "CY"));
        list.add(new Country("Colombia", "CO"));
        list.add(new Country("Comoras", "KM"));
        list.add(new Country("Congo", "CG"));
        list.add(new Country("Corea del Norte", "KP"));
        list.add(new Country("Corea del Sur", "KR"));
        list.add(new Country("Costa de Marfil", "CI"));
        list.add(new Country("Costa Rica", "CR"));
        list.add(new Country("Croacia", "HR"));
        list.add(new Country("Cuba", "CU"));
        list.add(new Country("Dinamarca", "DK"));
        list.add(new Country("Dominica", "DM"));
        list.add(new Country("Ecuador", "EC"));
        list.add(new Country("Egipto", "EG"));
        list.add(new Country("El Salvador", "SV"));
        list.add(new Country("Emiratos Árabes Unidos", "AE"));
        list.add(new Country("Eritrea", "ER"));
        list.add(new Country("Eslovaquia", "SK"));
        list.add(new Country("Eslovenia", "SI"));
        list.add(new Country("España", "ES"));
        list.add(new Country("Estados Unidos", "US"));
        list.add(new Country("Estonia", "EE"));
        list.add(new Country("Eswatini", "SZ"));
        list.add(new Country("Etiopía", "ET"));
        list.add(new Country("Filipinas", "PH"));
        list.add(new Country("Finlandia", "FI"));
        list.add(new Country("Fiyi", "FJ"));
        list.add(new Country("Francia", "FR"));
        list.add(new Country("Gabón", "GA"));
        list.add(new Country("Gambia", "GM"));
        list.add(new Country("Georgia", "GE"));
        list.add(new Country("Ghana", "GH"));
        list.add(new Country("Granada", "GD"));
        list.add(new Country("Grecia", "GR"));
        list.add(new Country("Guatemala", "GT"));
        list.add(new Country("Guinea", "GN"));
        list.add(new Country("Guinea-Bisáu", "GW"));
        list.add(new Country("Guinea Ecuatorial", "GQ"));
        list.add(new Country("Guyana", "GY"));
        list.add(new Country("Haití", "HT"));
        list.add(new Country("Honduras", "HN"));
        list.add(new Country("Hungría", "HU"));
        list.add(new Country("India", "IN"));
        list.add(new Country("Indonesia", "ID"));
        list.add(new Country("Irak", "IQ"));
        list.add(new Country("Irán", "IR"));
        list.add(new Country("Irlanda", "IE"));
        list.add(new Country("Islandia", "IS"));
        list.add(new Country("Islas Marshall", "MH"));
        list.add(new Country("Islas Salomón", "SB"));
        list.add(new Country("Israel", "IL"));
        list.add(new Country("Italia", "IT"));
        list.add(new Country("Jamaica", "JM"));
        list.add(new Country("Japón", "JP"));
        list.add(new Country("Jordania", "JO"));
        list.add(new Country("Kazajistán", "KZ"));
        list.add(new Country("Kenia", "KE"));
        list.add(new Country("Kirguistán", "KG"));
        list.add(new Country("Kiribati", "KI"));
        list.add(new Country("Kuwait", "KW"));
        list.add(new Country("Laos", "LA"));
        list.add(new Country("Lesoto", "LS"));
        list.add(new Country("Letonia", "LV"));
        list.add(new Country("Líbano", "LB"));
        list.add(new Country("Liberia", "LR"));
        list.add(new Country("Libia", "LY"));
        list.add(new Country("Liechtenstein", "LI"));
        list.add(new Country("Lituania", "LT"));
        list.add(new Country("Luxemburgo", "LU"));
        list.add(new Country("Macedonia del Norte", "MK"));
        list.add(new Country("Madagascar", "MG"));
        list.add(new Country("Malasia", "MY"));
        list.add(new Country("Malaui", "MW"));
        list.add(new Country("Maldivas", "MV"));
        list.add(new Country("Malí", "ML"));
        list.add(new Country("Malta", "MT"));
        list.add(new Country("Marruecos", "MA"));
        list.add(new Country("Mauricio", "MU"));
        list.add(new Country("Mauritania", "MR"));
        list.add(new Country("México", "MX"));
        list.add(new Country("Micronesia", "FM"));
        list.add(new Country("Moldavia", "MD"));
        list.add(new Country("Mónaco", "MC"));
        list.add(new Country("Mongolia", "MN"));
        list.add(new Country("Montenegro", "ME"));
        list.add(new Country("Mozambique", "MZ"));
        list.add(new Country("Namibia", "NA"));
        list.add(new Country("Nauru", "NR"));
        list.add(new Country("Nepal", "NP"));
        list.add(new Country("Nicaragua", "NI"));
        list.add(new Country("Níger", "NE"));
        list.add(new Country("Nigeria", "NG"));
        list.add(new Country("Noruega", "NO"));
        list.add(new Country("Nueva Zelanda", "NZ"));
        list.add(new Country("Omán", "OM"));
        list.add(new Country("Países Bajos", "NL"));
        list.add(new Country("Pakistán", "PK"));
        list.add(new Country("Palaos", "PW"));
        list.add(new Country("Panamá", "PA"));
        list.add(new Country("Papúa Nueva Guinea", "PG"));
        list.add(new Country("Paraguay", "PY"));
        list.add(new Country("Perú", "PE"));
        list.add(new Country("Polonia", "PL"));
        list.add(new Country("Portugal", "PT"));
        list.add(new Country("Reino Unido", "GB"));
        list.add(new Country("República Centroafricana", "CF"));
        list.add(new Country("República Checa", "CZ"));
        list.add(new Country("República del Congo", "CD"));
        list.add(new Country("República Dominicana", "DO"));
        list.add(new Country("Ruanda", "RW"));
        list.add(new Country("Rumania", "RO"));
        list.add(new Country("Rusia", "RU"));
        list.add(new Country("Samoa", "WS"));
        list.add(new Country("San Cristóbal y Nieves", "KN"));
        list.add(new Country("San Marino", "SM"));
        list.add(new Country("San Vicente y las Granadinas", "VC"));
        list.add(new Country("Santa Lucía", "LC"));
        list.add(new Country("Santo Tomé y Príncipe", "ST"));
        list.add(new Country("Senegal", "SN"));
        list.add(new Country("Serbia", "RS"));
        list.add(new Country("Seychelles", "SC"));
        list.add(new Country("Sierra Leona", "SL"));
        list.add(new Country("Singapur", "SG"));
        list.add(new Country("Siria", "SY"));
        list.add(new Country("Somalia", "SO"));
        list.add(new Country("Sri Lanka", "LK"));
        list.add(new Country("Sudáfrica", "ZA"));
        list.add(new Country("Sudán", "SD"));
        list.add(new Country("Sudán del Sur", "SS"));
        list.add(new Country("Suecia", "SE"));
        list.add(new Country("Suiza", "CH"));
        list.add(new Country("Surinam", "SR"));
        list.add(new Country("Tailandia", "TH"));
        list.add(new Country("Tanzania", "TZ"));
        list.add(new Country("Tayikistán", "TJ"));
        list.add(new Country("Timor Oriental", "TL"));
        list.add(new Country("Togo", "TG"));
        list.add(new Country("Tonga", "TO"));
        list.add(new Country("Trinidad y Tobago", "TT"));
        list.add(new Country("Túnez", "TN"));
        list.add(new Country("Turkmenistán", "TM"));
        list.add(new Country("Turquía", "TR"));
        list.add(new Country("Tuvalu", "TV"));
        list.add(new Country("Ucrania", "UA"));
        list.add(new Country("Uganda", "UG"));
        list.add(new Country("Uruguay", "UY"));
        list.add(new Country("Uzbekistán", "UZ"));
        list.add(new Country("Vanuatu", "VU"));
        list.add(new Country("Vaticano", "VA"));
        list.add(new Country("Venezuela", "VE"));
        list.add(new Country("Vietnam", "VN"));
        list.add(new Country("Yemen", "YE"));
        list.add(new Country("Yibuti", "DJ"));
        list.add(new Country("Zambia", "ZM"));
        list.add(new Country("Zimbabue", "ZW"));
        return list;
    }

}